steps:
  #build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/my-devops-practice-490010/gcpdevops-dev/$SHORT_SHA', '.']

  #push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'  
    args: ['push', 'us-east1-docker.pkg.dev/my-devops-practice-490010/gcpdevops-dev/$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s|us-east1-docker.pkg.dev/.*|us-east1-docker.pkg.dev/my-devops-practice-490010/gcpdevops-dev/$SHORT_SHA|g" gke.yml
        git config --global user.email "amar.iiitn224@gmail.com"
        git config --global user.name "CloudBuild"
        git add gke.yml
        git commit -m "Update image tag in gke.yml to $SHORT_SHA"
        git push origin HEAD:main  

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

