apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: us-east1-docker.pkg.dev/my-devops-practice-490010/gcpdevops-dev/40422a3
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  labels:
    app.kubernetes.io/manage-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: gcp
  type: LoadBalancer
